### ISSUE TITLE
failed to build HowToUse.ino

### ISSUE THREAD

**Issue by yasuhirok-git** [lovyan03/LovyanHAL#2]
Arduino IDE 2.0.3 + M5Stack-Core-ESP32で HowToUse.ino をビルドすると、以下のエラーが発生します。

- HowToUse.ino:24:35: error: 'class lhal::v0::LovyanHAL::GPIO_HAL' has no member named 'input_pullup'
   hal.Gpio.setMode(pin4, hal.Gpio.input_pullup);

- HowToUse.ino:33:35: error: 'class lhal::v0::LovyanHAL::GPIO_HAL' has no member named 'output'
   hal.Gpio.setMode(pin5, hal.Gpio.output);

- HowToUse.ino:48:25: error: 'class lhal::v0::LovyanHAL::GPIO_HAL' has no member named 'input'
   btn.setMode( hal.Gpio.input );

- HowToUse\HowToUse.ino:51:25: error: 'class lhal::v0::LovyanHAL::GPIO_HAL' has no member named 'output'
   led.setMode( hal.Gpio.output );

これらのエラーは以下のように修正すればよろしいでしょうか？
24行
hal.Gpio.setMode(pin4, **lhal::v0::gpio::input_pullup**);
33行
hal.Gpio.setMode(pin5, **lhal::v0::gpio::output**);
48行
btn.setMode( **lhal::v0::gpio::input** );
51行
led.setMode( **lhal::v0::gpio::output** );

**Comment by lovyan03** [comment]
@yasuhirok-git 
ご指摘ありがとうございます！
仕様をまだ決めきれておらず、色々と変更した影響が examplesに反映できていなかったようで、すみません。

基礎設計部分からしてまだ試作段階なので、ご意見などございましたら遠慮なくどうぞ…
現状だいぶ悩んでいて、イチから作り直すような案でもアリですので（汗

**Comment by yasuhirok-git** [comment]
了解です。試しにrp2040版を作ろうとしています。
